name: Docker Image CI

on: [push]

jobs:

  build-and-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: docker build . --file Dockerfile --tag nawaci
    - name: Unit Tests
      run: docker run nawaci /opt/nawabuild/unittests
    - name: Integration Tests
      run: docker run nawaci /opt/nawabuild/integrationtests
