name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      VERSION_TS: $(date +%s)

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/jatofg/nawa/nawa:0.1-${VERSION_TS}
    - name: Publish the Docker image
      run: docker login docker.pkg.github.com -u jatofg -p ${{ secrets.GITHUB_TOKEN }} && docker push docker.pkg.github.com/jatofg/nawa/nawa:0.1-${VERSION_TS}
