name: Docs
on: push

jobs:

  docs:
    name: Build and publish docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cd docs
          mkdir build
          cd build
          cmake -DNAWA_DOXYGEN_SOURCE_DIR=. -DNAWA_DOXYGEN_BINARY_DIR=docs/build ..
      - name: Build and publish docs
        uses: jatofg/doxygenize@1512ca5d53e36f257a6ae52171b80859959b7137
        with:
          doxygenconf: './docs/build/Doxyfile'
          htmloutput: './docs/build/docs_html/'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './v0.8/docs'