name: Docs
on: push

jobs:

  docs:
    name: Build and publish docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cd docs
          mkdir build
          cd build
          cmake -DNAWA_DOXYGEN_SOURCE_DIR=. -DNAWA_DOXYGEN_BINARY_DIR=docs/build ..
      - name: Build and publish docs
        uses: jatofg/doxygenize@793490df85e22534192e7b20689a6ed1bb97038e
        with:
          doxygenconf: './docs/build/Doxyfile'
          htmloutput: './docs/build/docs_html/'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './v0.8/docs'