name: build
on: push

jobs:

  docs:
    name: Build and publish docs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: |
          cd docs
          mkdir build
          cd build
          cmake ..
      - name: Build and publish docs
        uses: langroodi/doxygenize@4186fba316b72a7d790b1fff255f6a1dabc1db31
        with:
          doxygenconf: './docs/build/Doxyfile'
          htmloutput: './docs-out/'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './v0.8/docs'